"""Supervised warm-start from MILP demos (behaviour cloning).

Reads the trajectories produced by ``scripts/generate_milp_demos.py``
(each .pt contains per-step graph features + ``milp_actions``) and trains the
Graph-MAPPO actor to imitate the MILP's decisions via cross-entropy on the
actor's per-node action logits. The saved checkpoint can then be used to
resume real RL training:

    conda run -n pytorch python scripts/train/train_graph_mappo.py --checkpoint outputs/milp_imitation/milp_pretrain.pt

Usage:
    python scripts/supervised_train_milp_demos.py \
        --demos outputs/milp_demos --epochs 3 --batch-size 32 \
        --min-sr 0.5 --device cuda --run-name milp_imitation

Notes
-----
- The demos store the observation features the env produced; the model's
  forward path only needs node/edge features, edge_index and the per-node
  candidate/mask lists (not the env state), so observations are rebuilt from
  the stored arrays with a minimal ``EnvState``.
- Episodes whose executed ``success_rate < --min-sr`` are skipped, so
  low-quality MILP plans never poison the imitator.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from qkd_rl.rl.algos.checkpoint import load_checkpoint, save_checkpoint
from qkd_rl.core.config import ConfigValidator, deep_merge, load_config
from qkd_rl.env.factory import load_default_config
from qkd_rl.env.action_space import NodeActionSpace
from qkd_rl.env.graph_builder import GraphObservation
from qkd_rl.env.state import EnvState
from qkd_rl.rl.models.graph_mappo import GraphMAPPOActorCritic


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--demos", type=str, default="outputs/milp_demos",
                        help="Directory with episode_*.pt generated by generate_milp_demos.py.")
    parser.add_argument("--min-sr", type=float, default=0.0,
                        help="Skip demo episodes whose executed success rate is below this.")
    parser.add_argument("--limit", type=int, default=0,
                        help="Use only the first N trajectory steps in total (0 = all). Debugging aid.")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--config", type=str, default=None,
                        help="Optional extra YAML (e.g. configs/supervised_train.yaml) merged over the default chain.")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--run-name", type=str, default="milp_imitation")
    parser.add_argument("--checkpoint", type=str, default=None,
                        help="Resume from a previous imitation checkpoint.")
    parser.add_argument("--seed", type=int, default=7)
    return parser.parse_args()


def build_config(args: argparse.Namespace) -> dict:
    config = load_default_config(ROOT)
    config = deep_merge(config, load_config([ROOT / "configs" / "env_full.yaml"]))
    config = deep_merge(config, load_config([ROOT / "configs" / "global.yaml"]))
    if args.config:
        config = deep_merge(config, load_config([ROOT / args.config]))
    ConfigValidator().validate(config)
    return config


def load_steps(demos_dir: Path, min_sr: float, limit: int) -> list[dict]:
    """Load all (min-sr filtered) trajectory steps across demo episodes."""
    steps: list[dict] = []
    files = sorted(demos_dir.glob("episode_*.pt"))
    if not files:
        raise FileNotFoundError(f"No episode_*.pt found under {demos_dir}")
    skipped_eps = 0
    for f in files:
        data = torch.load(f, map_location="cpu", weights_only=False)
        sr = float(data.get("success_rate", 0.0))
        if sr < min_sr:
            skipped_eps += 1
            continue
        steps.extend(data["trajectory"])
        if limit and len(steps) >= limit:
            steps = steps[:limit]
            break
    print(f"loaded {len(steps)} steps from {len(files)} episodes "
          f"(skipped {skipped_eps} below min_sr={min_sr})", flush=True)
    if not steps:
        raise RuntimeError("no usable demo steps after min-sr filtering")
    return steps


def step_to_obs(step: dict) -> GraphObservation:
    """Rebuild a GraphObservation from the stored features.

    The model's forward path uses node/edge features, edge_index and the
    per-node candidate/mask lists; it never touches env state or the demand
    edge ids, so those are filled with minimal placeholders.
    """
    state = EnvState(
        t=int(step.get("t", 0)),
        qkp_snapshot={},
        pending_requests=[],
        edge_windows={},
        last_activated_edges=[],
    )
    return GraphObservation(
        node_features=step["node_features"],
        edge_index=[tuple(int(x) for x in e) for e in step["edge_index"]],
        edge_features=step["edge_features"],
        node_ids=list(step["node_ids"]),
        edge_ids=list(step["edge_ids"]),
        physical_edge_ids=list(step["physical_edge_ids"]),
        demand_edge_ids=[],
        action_candidates=step["action_candidates"],
        action_masks=step["action_masks"],
        state=state,
        raw_action_masks=step.get("raw_action_masks"),
    )


def _gold_edges(
    model: GraphMAPPOActorCritic,
    milp_actions: dict[str, tuple[str, str]],
) -> set[str]:
    """Derive the undirected gold link selections the MILP plan makes at one
    slot from its dual-port ``(tx_target, rx_source)`` actions.

    A node transmitting to a peer (tx!=idle) activates that pair, and a node
    accepting an incoming arc (rx=source) activates the (source,node) pair.
    Both collapse onto the same edge id pair, so we collect a deduplicated set
    of edge ids the RL global matching should reproduce.
    """
    gold: set[str] = set()
    idle = NodeActionSpace.IDLE
    for node_id, (tx, rx) in milp_actions.items():
        if tx != idle and tx != node_id:
            eid = model.action_space.arc_to_edge(node_id, tx)
            if eid is not None:
                gold.add(eid)
        if rx != idle and rx != node_id:
            eid = model.action_space.arc_to_edge(rx, node_id)
            if eid is not None:
                gold.add(eid)
    return gold


def imitation_loss(
    model: GraphMAPPOActorCritic,
    obs: GraphObservation,
    milp_actions: dict[str, tuple[str, str]],
    device: torch.device,
) -> torch.Tensor | None:
    """Train the actor's global edge scorer so its matching favours the MILP's
    per-slot link selections.

    The RL decision structure is a *directed matching* picked from the actor's
    per-edge ``edge_scores`` (one cross-node-comparable scalar per physical
    edge), not per-node one-hot logits. So the imitation loss is a binary
    cross-entropy on ``edge_scores`` against whether MILP activated that pair
    at this slot (positive if the edge is in the gold set, negative otherwise).
    This keeps the supervision on the exact signal the matching consumes.
    """
    out = model.forward(obs, device)
    edge_scores = out.edge_scores or {}
    if not edge_scores:
        return None
    gold = _gold_edges(model, milp_actions)
    losses: list[torch.Tensor] = []
    for edge_id, score in edge_scores.items():
        target = 1.0 if edge_id in gold else 0.0
        losses.append(
            F.binary_cross_entropy_with_logits(
                score.reshape(1),
                torch.tensor([target], dtype=score.dtype, device=device),
            )
        )
    return torch.stack(losses).mean()


def main() -> None:
    args = parse_args()
    torch.manual_seed(args.seed)
    device = torch.device(args.device)

    config = build_config(args)
    # Model needs the action space; build it from the config the same way the
    # env factory does, but release the env right away (the demos carry their
    # own observations).
    from qkd_rl.env.factory import build_env_from_config
    env = build_env_from_config(config)
    action_space = env.action_resolver.action_space
    env = None  # release; the demos carry their own observations

    model = GraphMAPPOActorCritic(action_space, config).to(device)
    optimizer = torch.optim.Adam(
        [
            {"params": model.encoder.parameters(), "lr": args.lr},
            {"params": model.actor.parameters(), "lr": args.lr},
            {"params": model.critic.parameters(), "lr": args.lr},
        ]
    )
    if args.checkpoint:
        data = load_checkpoint(args.checkpoint, device)
        model.load_state_dict(data.model_state)
        if data.optimizer_state is not None:
            try:
                optimizer.load_state_dict(data.optimizer_state)
            except ValueError as exc:
                print(f"optimizer state incompatible ({exc}); starting optimizer fresh")
        print(f"resumed imitation checkpoint: {args.checkpoint} (update={data.update})")

    steps = load_steps(Path(ROOT) / args.demos, args.min_sr, args.limit)

    output_dir = ROOT / "outputs" / args.run_name
    output_dir.mkdir(parents=True, exist_ok=True)
    log_path = output_dir / "imitation.log"

    def log(message: str) -> None:
        print(message, flush=True)
        with log_path.open("a", encoding="utf-8") as fh:
            fh.write(message + "\n")

    model.train()
    total_loss = 0.0
    total_samples = 0
    n_batches = 0
    for epoch in range(1, args.epochs + 1):
        epoch_loss = 0.0
        epoch_samples = 0
        for start in range(0, len(steps), args.batch_size):
            batch = steps[start : start + args.batch_size]
            losses: list[torch.Tensor] = []
            for step in batch:
                obs = step_to_obs(step)
                loss = imitation_loss(model, obs, step["milp_actions"], device)
                if loss is not None:
                    losses.append(loss)
            if not losses:
                continue
            loss = torch.stack(losses).mean()
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            b_loss = float(loss.detach().cpu())
            b_samples = len(losses)
            total_loss += b_loss * b_samples
            total_samples += b_samples
            epoch_loss += b_loss * b_samples
            epoch_samples += b_samples
            n_batches += 1
            if n_batches % 10 == 0:
                log(f"  epoch {epoch} batch {n_batches}: loss={b_loss:.5f} "
                    f"running_avg={total_loss / max(1, total_samples):.5f}")
        if epoch_samples == 0:
            log(f"epoch {epoch}: no usable steps (all actions missing from candidates?)")
            continue
        log(f"epoch {epoch}/{args.epochs}: samples={epoch_samples} "
            f"avg_loss={epoch_loss / epoch_samples:.5f} "
            f"overall={total_loss / max(1, total_samples):.5f}")

    checkpoint_path = output_dir / "milp_pretrain.pt"
    save_checkpoint(
        checkpoint_path,
        update=0,
        model=model,
        optimizer=optimizer,
        config=config,
        metrics={"imitation_loss": total_loss / max(1, total_samples), "steps": total_samples},
    )
    meta = {
        "demos": args.demos,
        "min_sr": args.min_sr,
        "limit": args.limit,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "device": str(device),
        "supervision": "milp_actions cross-entropy on actor logits",
        "steps_used": total_samples,
        "checkpoint": str(checkpoint_path),
    }
    with (output_dir / "imitation_meta.json").open("w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2, ensure_ascii=False)
    log(f"checkpoint: {checkpoint_path}")
    log("resume RL training with:")
    log(f"  conda run -n pytorch python scripts/train/train_graph_mappo.py --checkpoint {checkpoint_path}")


if __name__ == "__main__":
    main()